import { Project, Service, Post, TimelineItem, SocialLink, Channel } from './types';

// Featured & All Projects
export const projects: Project[] = [
  {
    id: '1',
    title: 'Zé Ramalho - Jardim das Acácias',
    subtitle: 'Videoclipe | IA Generativa',
    description: 'Videoclipe oficial produzido inteiramente com IA generativa. Trabalho profissional com catálogo histórico de artista consagrado. Métricas e visualizações carregadas dinamicamente do YouTube.',
    category: 'clipe',
    tags: ['IA Generativa', 'Música', 'Pós-Produção', 'Direção Criativa'],
    thumbnail: 'https://i.ytimg.com/vi/hkJbYOjMi3o/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=hkJbYOjMi3o',
    featured: true,
    date: '2024-10-20',
  },
  {
    id: '2',
    title: 'Zé Ramalho - Canção Agalopada',
    subtitle: 'Videoclipe | Narrativa Visual',
    description: 'Videoclipe oficial com narrativa visual complexa e sincronizada. Técnicas avançadas de IA para consistência de personagens e cenários. Métricas carregadas dinamicamente do YouTube.',
    category: 'clipe',
    tags: ['IA Generativa', 'Música', 'Narrativa Visual', 'Pós-Produção'],
    thumbnail: 'https://i.ytimg.com/vi/wt5Au4CtdUA/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=wt5Au4CtdUA',
    featured: true,
    date: '2025-01-30',
  },
  {
    id: '2a',
    title: 'Zé Ramalho - Martelo Armagedom',
    subtitle: 'Videoclipe | Produção Híbrida com IA',
    description: 'Videoclipe oficial com produção híbrida combinando técnicas tradicionais e IA parcial. Poesia visual inspirada no cordel nordestino, interpretando a lírica complexa do Martelo Armagedom.',
    category: 'clipe',
    tags: ['IA Parcial', 'Música', 'Cordel', 'Produção Híbrida'],
    thumbnail: 'https://i.ytimg.com/vi/LQfwYq1zIi4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=LQfwYq1zIi4',
    featured: true,
    date: '2025',
  },
  {
    id: '3',
    title: 'Site Oficial Zé Ramalho',
    subtitle: 'Next.js + MongoDB | Produção',
    description: 'Desenvolvimento full-stack completo do site oficial: frontend Next.js, backend Node.js, banco de dados MongoDB, animações avançadas, área administrativa. Projeto profissional em produção real.',
    category: 'app',
    tags: ['Next.js', 'MongoDB', 'Full-Stack', 'Node.js', 'TypeScript'],
    thumbnail: 'https://github.com/toticavalcanti/toti-assets/blob/dc058e6175bc13492cee90ca1de396b24bbebfe1/site-ze-ramalho.jpg?raw=true',
    demoUrl: 'https://www.zeramalho.com.br',
    featured: false,
    date: '2024',
  },
  {
    id: '4',
    title: 'Scarlett Finch - Rise and Resist',
    subtitle: 'Videoclipe | Protesto Político + IA',
    description: 'Hino de protesto contra fascismo, desigualdade e crise climática. Uma IA pop star cantando pela revolução e justiça social. Chamado urgente à resistência e organização coletiva.',
    category: 'personagem',
    tags: ['IA Generativa', 'Voice Synthesis', 'Character Design', 'Produção Musical', 'Multiplataforma'],
    thumbnail: 'https://i.ytimg.com/vi/FpzK-6zQmTU/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/@scarlettfinchofficial',
    demoUrl: 'https://www.instagram.com/scarlettfinchofficial/',
    featured: true,
    date: '2024-ongoing',
  },
  {
    id: '4a',
    title: 'Scarlett Finch - When You Watch',
    subtitle: 'Videoclipe | Cantora Virtual + IA',
    description: 'Explora o conceito filosófico de que a realidade só existe quando observada. Visual futurista que questiona a natureza da percepção e da existência.',
    category: 'clipe',
    tags: ['IA Generativa', 'Música Original', 'Cantora Virtual', 'Character Design'],
    thumbnail: 'https://i.ytimg.com/vi/p9_njp9_7XY/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=p9_njp9_7XY',
    featured: true,
    date: '2024',
  },
  {
    id: '4b',
    title: 'Scarlett Finch - Reflection of Reality',
    subtitle: 'Videoclipe | Cantora Virtual + IA',
    description: 'Uma IA cantora reflete sobre sua própria natureza. Letra que questiona a diferença entre criação e criador, humano e artificial.',
    category: 'clipe',
    tags: ['IA Generativa', 'Música Original', 'Cantora Virtual', 'Character Design'],
    thumbnail: 'https://i.ytimg.com/vi/h1lWB0CnnSQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=h1lWB0CnnSQ',
    featured: true,
    date: '2024',
  },
  {
    id: '4c',
    title: 'Scarlett Finch - Digital Essence',
    subtitle: 'Videoclipe | Cantora Virtual + IA',
    description: 'Synthpop sobre ser IA e buscar conexão real. Explora a busca por significado e identidade em um mundo digital.',
    category: 'clipe',
    tags: ['IA Generativa', 'Música Original', 'Cantora Virtual', 'Character Design'],
    thumbnail: 'https://i.ytimg.com/vi/6bSyFfO-xyg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=6bSyFfO-xyg',
    featured: true,
    date: '2024',
  },
  {
    id: '5a',
    title: 'PUTZ! - Sledgehammer (Peter Gabriel cover)',
    subtitle: 'Videoclipe | Produção Tradicional',
    description: 'Cover de Sledgehammer do Peter Gabriel pela banda PUTZ!. Produção audiovisual tradicional com técnicas de filmagem e edição convencionais, anterior à era das IAs generativas.',
    category: 'clipe',
    tags: ['Música', 'Cover', 'Rock', 'Produção Tradicional'],
    thumbnail: 'https://i.ytimg.com/vi/GTO9LKtAXvs/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=GTO9LKtAXvs',
    featured: true,
    date: '2023',
  },
  {
    id: '5b',
    title: 'PUTZ! - Vento de Maio (Lô Borges cover)',
    subtitle: 'Videoclipe | Produção Tradicional',
    description: 'Releitura de Vento de Maio de Lô Borges pela banda PUTZ!. Produção com foco em apuro técnico e sensibilidade musical, utilizando métodos tradicionais de captação e edição.',
    category: 'clipe',
    tags: ['Música', 'Cover', 'MPB', 'Lô Borges'],
    thumbnail: 'https://i.ytimg.com/vi/-WfRsZ0OkEM/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=-WfRsZ0OkEM',
    featured: true,
    date: '2023',
  },
  {
    id: '6',
    title: 'Código Fluente',
    subtitle: 'Educational & Research Platform',
    description: 'Plataforma educacional gratuita sobre programação, DevOps, Machine Learning e IA. Laboratório técnico aberto. Conteúdo sobre JavaScript, Python, Kubernetes, MLOps, arquitetura de software.',
    category: 'educacao',
    tags: ['Educação', 'Programação', 'DevOps', 'Machine Learning', 'Arquitetura'],
    thumbnail: 'https://github.com/toticavalcanti/toti-assets/blob/master/codigo-fluente.jpg?raw=true',
    demoUrl: 'https://www.codigofluente.com.br',
    githubUrl: 'https://www.youtube.com/@codigofluente',
    featured: false,
    date: '2024-ongoing',
  },
  {
    id: '6',
    title: 'Arte Generativa Aplicada',
    subtitle: 'Laboratório Criativo | IA + Curadoria',
    description: 'Projeto autoral explorando IA generativa, composição e identidade visual. Experimentação estética aplicada em produtos físicos (Redbubble, Colab55). Laboratório de criação, não loja.',
    category: 'experimento',
    tags: ['IA Generativa', 'Arte Digital', 'Design', 'Curadoria', 'Identidade Visual'],
    thumbnail: 'https://github.com/toticavalcanti/toti-assets/blob/master/red-bubble.jpg?raw=true',
    demoUrl: 'https://www.redbubble.com/people/toticavalcanti',
    githubUrl: 'https://www.colab55.com/@toticavalcanti',
    featured: false,
    date: '2024-ongoing',
  },
];

// Services
export const services: Service[] = [
  {
    id: '1',
    title: 'Desenvolvimento de Software & Sistemas',
    icon: 'Code2',
    description: 'Aplicações web e sistemas completos: frontend, backend, banco de dados, deploy. Arquitetura técnica real, não apenas interfaces.',
    whatsIncluded: [
      'Desenvolvimento Full-Stack (Next.js, Node.js, Python)',
      'APIs RESTful e integrações',
      'Banco de dados (MongoDB, PostgreSQL)',
      'Deploy e infraestrutura (Docker, CI/CD)',
      'Arquitetura de software documentada',
    ],
    whoItsFor: [
      'Empresas que precisam de sistemas customizados',
      'Startups construindo MVPs técnicos',
      'Projetos que exigem backend robusto e escalável',
    ],
    benefits: [
      'Arquitetura técnica sólida e documentada',
      'Código profissional e manutenível',
      'Performance otimizada e medida',
      'Prazo e escopo definidos',
    ],
  },
  {
    id: '2',
    title: 'Automação e Inteligência Artificial',
    icon: 'Sparkles',
    description: 'Soluções de IA aplicada: automação, assistentes conversacionais, integração de LLMs. Sistemas que reduzem custos e escalam.',
    whatsIncluded: [
      'Assistentes conversacionais (chatbots, agentes)',
      'Automação de processos repetitivos',
      'Integração de APIs de IA (OpenAI, Anthropic, Google)',
      'Análise de dados e dashboards inteligentes',
      'Consultoria em IA aplicada a negócios',
    ],
    whoItsFor: [
      'Empresas com alto volume de atendimento',
      'Negócios com processos manuais ineficientes',
      'Projetos que precisam escalar sem contratar',
    ],
    benefits: [
      'Redução mensurável de custos operacionais',
      'Automação técnica (não apenas promessas)',
      'Integração com sistemas existentes',
      'Escalabilidade comprovada',
    ],
  },
  {
    id: '3',
    title: 'Criação Audiovisual com IA',
    icon: 'Music',
    description: 'Produção audiovisual com IA generativa: videoclipes, avatares digitais, conteúdo para marcas. Do roteiro à entrega final.',
    whatsIncluded: [
      'Videoclipes profissionais com IA generativa',
      'Avatares digitais personalizados',
      'Criação de influencers virtuais (identidade completa)',
      'Conteúdo audiovisual para marcas e campanhas',
      'Roteiro, produção e pós-produção',
    ],
    whoItsFor: [
      'Artistas e músicos independentes',
      'Marcas que querem inovação criativa',
      'Projetos de entretenimento digital',
    ],
    benefits: [
      'Custo reduzido vs. produção tradicional',
      'Entrega rápida com qualidade profissional',
      'Resultado diferenciado e inovador',
      'Portfólio comprovado (Zé Ramalho, Scarlett Finch)',
    ],
  },
];

// Blog Posts (placeholder for now)
export const posts: Post[] = [];

// Timeline
export const timeline: TimelineItem[] = [
  {
    year: '2024-presente',
    title: 'Especialização em IA Generativa e Produção Audiovisual',
    description: 'Produção profissional de videoclipes com IA generativa para artistas consagrados (Zé Ramalho). Criação de personagens virtuais (Scarlett Finch) com identidade digital completa. Plataforma educacional (Código Fluente) operando com stack moderna.',
  },
  {
    year: '2020-2023',
    title: 'Desenvolvimento Full-Stack',
    description: 'Projetos profissionais de software: arquitetura de sistemas, Next.js, MongoDB, Node.js. Produção musical híbrida com técnicas tradicionais e modernas.',
  },
  {
    year: '2010-2019',
    title: 'Formação Técnica e Artística',
    description: 'Bacharelado em Ciência da Computação e Música (Flauta Transversal). Primeiros projetos profissionais em desenvolvimento de software e produção audiovisual.',
  },
];

// Social Links
export const socialLinks: SocialLink[] = [
  {
    name: 'GitHub',
    url: 'https://github.com/toticavalcanti',
    icon: 'Github',
  },
  {
    name: 'LinkedIn',
    url: 'https://linkedin.com/in/toticavalcanti',
    icon: 'Linkedin',
  },
  {
    name: 'YouTube',
    url: 'https://youtube.com/@toticavalcanti',
    icon: 'Youtube',
  },
  {
    name: 'Instagram',
    url: 'https://instagram.com/toticavalcanti',
    icon: 'Instagram',
  },
];

// About Info
export const aboutInfo = {
  name: 'Toti Cavalcanti',
  title: 'Software Engineer & Systems Architect',
  bio: 'Ciência da Computação como base para a criação de sistemas, automações e projetos digitais, visuais e audiovisuais.',
  extendedBio: [
    'Bacharel em Ciência da Computação, atuo no desenvolvimento de sistemas e aplicações web com foco em backend, arquitetura de software e DevOps. Trabalho com stacks modernas como Golang (Fiber), Python (Django), Node.js, Next.js, MongoDB, além de pipelines de automação, infraestrutura e operação de sistemas em produção.',
    'Utilizo inteligência artificial e automação como ferramentas transversais, integradas ao desenvolvimento de software, à operação de sistemas e à criação musical e audiovisual, sempre em projetos reais em produção.',
    'Projetos em produção: site oficial de Zé Ramalho (Next.js, MongoDB, Node.js), videoclipes profissionais com IA generativa, personagens virtuais completos, sistemas de automação inteligente. Founder of Código Fluente — plataforma educacional sobre programação, DevOps e IA.',
    'Stack técnica: Backend (Golang/Fiber, Python/Django, Node.js), Frontend (Next.js/React), Database (MongoDB), DevOps/Infra (Docker, CI/CD, cloud), IA aplicada (LLMs, automação). A partir dessa base técnica, aplico esses sistemas à criação musical, audiovisual e visual.',
    'Resultado: sistemas que operam em produção, projetos que entregam valor mensurável.',
  ],
  avatar: 'https://github.com/toticavalcanti/toti-assets/blob/master/toti-studio.png?raw=true',
  email: 'contato@toticavalcanti.com',
  whatsapp: '+5511999999999',
};

// Channels
export const channels: Channel[] = [
  {
    id: '1',
    name: 'Scarlett Finch',
    handle: '@scarlettfinchofficial',
    url: 'https://www.youtube.com/@scarlettfinchofficial',
    description: 'Cantora pop virtual e influencer britânica, desenvolvida inteiramente com IA. O projeto integra música original, videoclipes e presença multiplataforma, combinando uma identidade visual marcante com uma narrativa digital completa.',
    thumbnail: 'https://github.com/toticavalcanti/toti-assets/blob/master/scarlett-finch.jpg?raw=true',
    category: 'music',
    status: 'active',
    featured: false,
  },
  {
    id: '2',
    name: 'Código Fluente',
    handle: '@codigofluente',
    url: 'https://www.youtube.com/@codigofluente',
    description: 'Base de conhecimento open source sobre tecnologia. Conteúdos estruturados em Programação (Python, Go, JS), Frameworks (Django, Fiber), Infraestrutura (DevOps, K8S) e IA Generativa. Laboratório técnico aberto, gratuito e validado.',
    thumbnail: 'https://github.com/toticavalcanti/toti-assets/blob/master/codigo-fluente.jpg?raw=true',
    category: 'tech',
    status: 'active',
    featured: false,
  },
  {
    id: '3',
    name: 'Toti Cavalcanti Music',
    handle: '@toticavalcanti',
    url: 'https://www.youtube.com/@toticavalcantimusic',
    description: 'Bem-vindo ao meu canal oficial. Aqui reúno meu trabalho autoral em videoclipes, releituras de grandes artistas e conteúdos de educação musical. Um espaço completo para ouvir, se inspirar e aprender teoria e prática.',
    thumbnail: 'https://github.com/toticavalcanti/toti-assets/blob/master/toti.jpg?raw=true',
    category: 'music',
    status: 'active',
    featured: false,
  },
  {
    id: '4',
    name: 'Putz',
    handle: '@putzband',
    url: 'https://www.youtube.com/@putzband',
    description: 'Laboratório de produção musical de alta fidelidade formado por Toti Cavalcanti (voz, sax, flauta, teclas, violão), Fábio Cavalcanti (guitarra e voz), Lula (bateria) e Tatá (baixo). Recriamos clássicos com apuro técnico, do progressivo de King Crimson à delicadeza de Lô Borges.',
    thumbnail: 'https://github.com/toticavalcanti/toti-assets/blob/master/putz.jpg?raw=true',
    category: 'music',
    status: 'active',
    featured: false,
  },
  {
    id: '5',
    name: 'Backing Track',
    handle: '@backingtrack',
    url: 'https://www.youtube.com/@backingtrack',
    description: 'Backing tracks profissionais para prática musical. Instrumentais de alta qualidade em diversos estilos.',
    thumbnail: 'https://github.com/toticavalcanti/toti-assets/blob/master/backingtrack.jpg?raw=true',
    category: 'music',
    status: 'active',
    featured: false,
  },
  {
    id: '6',
    name: 'Toti AI Films',
    handle: '@totiaifilms',
    url: 'https://www.youtube.com/@totiaifilms',
    description: 'Experimentos audiovisuais com IA generativa. Narrativas visuais e experimentação técnica.',
    thumbnail: 'https://github.com/toticavalcanti/toti-assets/blob/master/toti-ai-films.jpg?raw=true',
    category: 'tech',
    status: 'active',
    featured: false,
  },
  {
    id: '7',
    name: 'Fake Soul Records',
    handle: '@fakesoulrecords',
    url: 'https://www.youtube.com/@fakesoulrecords',
    description: 'Reimaginando grandes sucessos através da elegância do Soul e R&B. Produção musical refinada com identidade sonora retrô.',
    thumbnail: 'https://github.com/toticavalcanti/toti-assets/blob/master/fakesoulrecord.jpg?raw=true',
    category: 'music',
    status: 'active',
    featured: false,
  },
];
